Repository Sahil-Connect/sahil, pull requests merged in 2023-08, with the labels that each got.

#1 Turbo Repo Implementation
  .eslintrc.js
  .gitignore
  .npmrc
  .nvmrc
  README.md
  apps/agent/.eslintrc.json
  apps/agent/.gitignore
  apps/agent/README.md
  apps/agent/next.config.js
  apps/agent/package.json
  apps/agent/postcss.config.js
  apps/agent/public/next.svg
  apps/agent/public/vercel.svg
  apps/agent/src/app/favicon.ico
  apps/agent/src/app/globals.css
  apps/agent/src/app/layout.tsx
  apps/agent/src/app/page.tsx
  apps/agent/tailwind.config.ts
  apps/agent/tsconfig.json
  apps/docs/.eslintrc.js
  apps/docs/.gitignore
  apps/docs/README.md
  apps/docs/app/layout.tsx
  apps/docs/app/page.tsx
  apps/docs/next-env.d.ts
  apps/docs/next.config.js
  apps/docs/package.json
  apps/docs/tsconfig.json
  apps/web/.eslintrc.js
  apps/web/.gitignore
  apps/web/README.md
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/next-env.d.ts
  apps/web/next.config.js
  apps/web/package.json
  apps/web/tsconfig.json
  package.json
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/tsconfig/base.json
  packages/tsconfig/nextjs.json
  packages/tsconfig/package.json
  packages/tsconfig/react-library.json
  packages/ui/Button.tsx
  packages/ui/Header.tsx
  packages/ui/index.tsx
  packages/ui/package.json
  packages/ui/tsconfig.json
  packages/ui/turbo/generators/config.ts
  packages/ui/turbo/generators/templates/component.hbs
  turbo.json
  yarn.lock
Labels: enhancement

#2 [SAH-1]: Directory Structure
  apps/agent/grafbase/grafbase.config.ts
  apps/agent/package.json
  apps/agent/src/app/clients/page.tsx
  apps/agent/src/app/layout.tsx
  apps/agent/src/app/page.tsx
  apps/agent/src/app/profile/page.tsx
  apps/agent/src/app/suppliers/page.tsx
  apps/agent/src/lib/graphql/apolloClient.ts
  apps/agent/src/styles/globals.css
  apps/agent/src/ui/navbar.tsx
  apps/agent/tailwind.config.ts
  yarn.lock
Labels: enhancement, good first issue

#4 [SAH-2]: Switch to Pages Router from App Router
  apps/agent/README.md
  apps/agent/grafbase/grafbase.config.ts
  apps/agent/next.config.js
  apps/agent/package.json
  apps/agent/public/favicon.ico
  apps/agent/src/app/layout.tsx
  apps/agent/src/app/page.tsx
  apps/agent/src/pages/_app.tsx
  apps/agent/src/pages/_document.tsx
  apps/agent/src/pages/api/hello.ts
  apps/agent/src/pages/clients/index.tsx
  apps/agent/src/pages/index.tsx
  apps/agent/src/pages/profile/index.tsx
  apps/agent/src/pages/suppliers/index.tsx
  apps/agent/tailwind.config.ts
  apps/agent/tsconfig.json
  yarn.lock
Labels: enhancement

#18 [SAH-12]: Implement Auth
  apps/agent/src/pages/_app.tsx
  apps/agent/src/pages/api/auth/[...nextauth].ts
  apps/agent/src/pages/auth/new.tsx
  apps/agent/src/pages/auth/signin.tsx
  apps/agent/src/pages/clients/index.tsx
Labels: enhancement 🌻, work_in_progress 🐣, front-end 🦋, backend 🐝

#12 [SAH-3]: Register new business
  apps/agent/src/componens/clients/ClientOverviewCard.tsx
  apps/agent/src/componens/clients/ListClients.tsx
  apps/agent/src/components/clients/ClientOverviewCard.tsx
  apps/agent/src/components/clients/InsertNewClient.tsx
  apps/agent/src/components/clients/ListClients.tsx
  apps/agent/src/hooks/clients.ts
  apps/agent/src/hooks/users.ts
  apps/agent/src/lib/graphql/mutations/clients.ts
  apps/agent/src/lib/graphql/mutations/users.ts
  apps/agent/src/lib/graphql/queries/clients.ts
  apps/agent/src/pages/clients/index.tsx
  apps/agent/src/pages/index.tsx
  packages/ui/Button.tsx
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#21 [SAH-7]: Configure DaisyUI
  .gitignore
  .vscode/settings.json
  apps/agent/public/logo.png
  apps/agent/src/components/navbar/Navbar.tsx
  apps/agent/src/pages/_document.tsx
  apps/agent/src/pages/index.tsx
  apps/agent/src/pages/suppliers/index.tsx
  apps/agent/src/styles/globals.css
  apps/agent/tailwind.config.ts
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋
