Repository Sahil-Connect/sahil, pull requests merged in 2023-10, with the labels that each got.

#34 [SAH-21]: Add Hero Section
  apps/website/public/service-1.svg
  apps/website/public/service-2.svg
  apps/website/public/service-3.svg
  apps/website/public/service-4.svg
  apps/website/public/vector-1.svg
  apps/website/public/vector-2.svg
  apps/website/src/app/page.tsx
  apps/website/src/components/Sections/Hero.tsx
  apps/website/src/components/Sections/Services.tsx
  apps/website/src/data/dummyData.tsx
  yarn.lock
Labels: enhancement 🌻, good first issue 🌈, ready_for_review 🍀, front-end 🦋

#36 [SAH-22]: Add Other Sections on Landing Page
  apps/website/public/about.png
  apps/website/public/cta.png
  apps/website/public/feature-1.svg
  apps/website/public/feature-2.svg
  apps/website/public/feature-3.svg
  apps/website/src/app/page.tsx
  apps/website/src/components/Sections/About.tsx
  apps/website/src/components/Sections/Cta.tsx
  apps/website/src/components/Sections/Features.tsx
  apps/website/src/components/Sections/Services.tsx
  apps/website/src/components/UI/Overlay.tsx
  apps/website/src/data/constants.tsx
  apps/website/src/data/dummyData.tsx
  apps/website/src/styles/globals.css
Labels: enhancement 🌻, good first issue 🌈, ready_for_review 🍀, front-end 🦋

#38 [SAH-23]: Add Faqs & Footer Sections on Landing Page
  apps/website/src/app/page.tsx
  apps/website/src/components/Sections/Faqs.tsx
  apps/website/src/components/UI/Footer.tsx
  apps/website/src/data/constants.tsx
Labels: enhancement 🌻, good first issue 🌈, front-end 🦋

#39 [SAH-17]: Develop Supplier Profile Page
  apps/agent/src/components/Suppliers/Clients.tsx
  apps/agent/src/components/Suppliers/LatestOrders.tsx
  apps/agent/src/components/Suppliers/ProductsList.tsx
  apps/agent/src/components/Suppliers/ServiceZones.tsx
  apps/agent/src/components/Suppliers/SupplierOverviewCard.tsx
  apps/agent/src/components/Suppliers/SupplierProfileOverview.tsx
  apps/agent/src/components/Suppliers/index.ts
  apps/agent/src/lib/graphql/queries/suppliers.ts
  apps/agent/src/pages/suppliers/[supplierId].tsx
  apps/agent/src/pages/suppliers/index.tsx
Labels: good first issue 🌈, work_in_progress 🐣, front-end 🦋

#40 [SAH-16]: Add Business Page with Contact Info and Overview
  apps/agent/src/components/Businesses/BusinessOrderHistory.tsx
  apps/agent/src/components/Businesses/BusinessOverviewCard.tsx
  apps/agent/src/components/Businesses/BusinessProfileOverview.tsx
  apps/agent/src/components/Businesses/BusinessRegistrationForm/BusinessInfoSummary.tsx
  apps/agent/src/components/Businesses/BusinessRegistrationForm/index.tsx
  apps/agent/src/components/Businesses/index.tsx
  apps/agent/src/components/Suppliers/LatestOrders.tsx
  apps/agent/src/components/Suppliers/ProductsList.tsx
  apps/agent/src/components/Suppliers/SupplierOrderHistory.tsx
  apps/agent/src/components/Suppliers/SupplierProfileOverview.tsx
  apps/agent/src/components/Suppliers/index.ts
  apps/agent/src/hooks/businesses.ts
  apps/agent/src/lib/graphql/queries/businesses.ts
  apps/agent/src/pages/businesses/[businessId].tsx
  apps/agent/src/pages/businesses/index.tsx
  apps/agent/src/pages/businesses/new/[...step].tsx
  apps/agent/src/pages/businesses/orders/index.tsx
  apps/agent/src/pages/suppliers/[supplierId].tsx
  apps/agent/tailwind.config.ts
Labels: good first issue 🌈, work_in_progress 🐣, front-end 🦋

#43 Suppliers List
  apps/agent/src/components/Suppliers/ListSuppliers.tsx
  apps/agent/src/components/Suppliers/SupplierOverviewCard.tsx
  apps/agent/src/hooks/suppliers.ts
  apps/agent/src/lib/graphql/queries/suppliers.ts
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#44 Supplier Details Page
  apps/agent/src/components/Suppliers/EditProductModal.tsx
  apps/agent/src/components/Suppliers/FilterSuppliersModal.tsx
  apps/agent/src/components/Suppliers/ListSuppliers.tsx
  apps/agent/src/components/Suppliers/ProductsList.tsx
  apps/agent/src/components/Suppliers/SupplierOrderHistory.tsx
  apps/agent/src/components/Suppliers/SupplierOverviewCard.tsx
  apps/agent/src/components/Suppliers/SupplierProductList.tsx
  apps/agent/src/components/Suppliers/SupplierProducts.tsx
  apps/agent/src/components/Suppliers/SupplierProfileOverview.tsx
  apps/agent/src/components/Suppliers/index.ts
  apps/agent/src/hooks/suppliers.ts
  apps/agent/src/lib/graphql/mutations/suppliers.ts
  apps/agent/src/lib/graphql/queries/suppliers.ts
  apps/agent/src/pages/suppliers/[supplierId].tsx
  apps/agent/src/pages/suppliers/index.tsx
  apps/agent/tailwind.config.ts
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#42 [SAH-10]: Place Order
  apps/agent/next.config.js
  apps/agent/package.json
  apps/agent/src/components/Orders/OrderProcessingForm/DeliveryDetails.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/OrderDetails.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/OrderFormSteps.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/OrderSummary.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/PaymentDetails.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/ProductSelection.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/StepsPaginator.tsx
  apps/agent/src/components/Orders/OrderProcessingForm/index.ts
  apps/agent/src/components/Orders/OrdersList.tsx
  apps/agent/src/components/Orders/ProductsCatalogue.tsx
  apps/agent/src/components/Orders/RecommendedSuppliers.tsx
  apps/agent/src/components/Orders/constants.ts
  apps/agent/src/components/Orders/index.ts
  apps/agent/src/components/Orders/types.ts
  apps/agent/src/components/Suppliers/SupplierOrderHistory.tsx
  apps/agent/src/components/Suppliers/SupplierRegistrationForm/PreviewSupplierInfo.tsx
  apps/agent/src/components/Suppliers/SupplierRegistrationForm/SupplierBasicInfoForm.tsx
  apps/agent/src/components/Suppliers/SupplierRegistrationForm/SupplierBusinessInfoForm.tsx
  apps/agent/src/components/Suppliers/SupplierRegistrationForm/SupplierPreferencesForm.tsx
  apps/agent/src/hooks/businesses.ts
  apps/agent/src/hooks/orders.ts
  apps/agent/src/hooks/products.ts
  apps/agent/src/hooks/useOrderFormStore.ts
  apps/agent/src/hooks/useOrderItemsStore.ts
  apps/agent/src/hooks/useSupplierFormStore.ts
  apps/agent/src/lib/graphql/mutations/orders.ts
  apps/agent/src/lib/graphql/queries/orders.ts
  apps/agent/src/lib/graphql/queries/products.ts
  apps/agent/src/pages/businesses/[businessId].tsx
  apps/agent/src/pages/index.tsx
  apps/agent/src/pages/orders/[orderId].tsx
  apps/agent/src/pages/orders/index.tsx
  apps/agent/src/pages/orders/new/[...step].tsx
  apps/agent/src/pages/orders/track.tsx
  apps/agent/src/pages/suppliers/new/[[...step]].tsx
  packages/lib/currency.ts
  packages/lib/dates.ts
  packages/lib/index.ts
  packages/lib/orders.ts
  packages/lib/package.json
  packages/lib/tailwindConfig.ts
  packages/ui/Button.tsx
  packages/ui/Card/Card.tsx
  packages/ui/Card/index.ts
  packages/ui/FormControl.tsx
  packages/ui/Input.tsx
  packages/ui/JoinGrid.tsx
  packages/ui/MultiStepForm/FormSteps.tsx
  packages/ui/MultiStepForm/StepsPaginator.tsx
  packages/ui/MultiStepForm/index.ts
  packages/ui/Select.tsx
  packages/ui/Steps.tsx
  packages/ui/index.tsx
Labels: enhancement 🌻, work_in_progress 🐣, front-end 🦋, backend 🐝

#52 [SAH-27]: List Couriers
  apps/agent/src/Couriers/CourierOverview.tsx
  apps/agent/src/Couriers/CourierProfileOverview.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/AddressInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierFormSteps.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierSummary.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/FormStepsPaginator.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/VehicleInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/index.tsx
  apps/agent/src/Couriers/ListCouriers.tsx
  apps/agent/src/Couriers/constants.ts
  apps/agent/src/Couriers/index.tsx
  apps/agent/src/Couriers/types.ts
  apps/agent/src/hooks/couriers.ts
  apps/agent/src/hooks/useCourierFormStore.tsx
  apps/agent/src/lib/graphql/mutations/couriers.ts
  apps/agent/src/lib/graphql/queries/couriers.ts
  apps/agent/src/pages/businesses/register/[...step].tsx
  apps/agent/src/pages/couriers/[courierId].tsx
  apps/agent/src/pages/couriers/index.tsx
  apps/agent/src/pages/couriers/register/[...step].tsx
Labels: work_in_progress 🐣, front-end 🦋

#46 [SAH-24]: Improve Agent UI & List Businesses
  apps/agent/.env.example
  apps/agent/src/Businesses/BusinessOverviewCard.tsx
  apps/agent/src/Businesses/ListBusinesses.tsx
  apps/agent/src/components/UI/Navbar.tsx
  apps/agent/src/pages/_document.tsx
  apps/agent/src/pages/businesses/index.tsx
  apps/agent/tailwind.config.ts
Labels: enhancement 🌻, good first issue 🌈, ready_for_review 🍀, front-end 🦋
