Repository Sahil-Connect/sahil, pull requests merged in 2023-11, with the labels that each got.

#57 [SAH-29]: Process Payments
  apps/payments/.env.example
  apps/payments/package.json
  apps/payments/src/index.ts
  apps/payments/tsconfig.json
  packages/tsconfig/base.json
  yarn.lock
Labels: ready_for_review 🍀, backend 🐝

#59 [SAH-30]: Maps API
  .gitignore
  apps/maps/package.json
  apps/maps/src/index.ts
  apps/maps/tsconfig.json
  apps/maps_api/src/index.ts
  apps/maps_api/src/places/resolvers.ts
  apps/maps_api/src/places/type_defs.ts
  yarn.lock
Labels: work_in_progress 🐣, backend 🐝

#67 [SAH-25]: Courier Registration Form
  apps/agent/src/Couriers/CourierOverviewCard.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/AddressInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierContactDetails.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierFormSteps.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierFormStepsPaginator.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierFormSummary.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierPersonalInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierSummary.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/CourierVehicleInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/FormStepsPaginator.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/VehicleInfo.tsx
  apps/agent/src/Couriers/CourierRegistrationForm/index.tsx
  apps/agent/src/Couriers/ListCouriers.tsx
  apps/agent/src/Couriers/constants.ts
  apps/agent/src/Suppliers/SupplierRegistrationForm/PreviewSupplierInfo.tsx
  apps/agent/src/Suppliers/SupplierRegistrationForm/SupplierBasicInfoForm.tsx
  apps/agent/src/Suppliers/SupplierRegistrationForm/SupplierBusinessInfoForm.tsx
  apps/agent/src/Suppliers/SupplierRegistrationForm/SupplierPreferencesForm.tsx
  apps/agent/src/hooks/couriers.ts
  apps/agent/src/hooks/useBusinessFormStore.ts
  apps/agent/src/hooks/useCourierFormStore.tsx
  apps/agent/src/hooks/useSupplierFormStore.ts
  apps/agent/src/lib/graphql/mutations/couriers.ts
  apps/agent/src/lib/graphql/queries/couriers.ts
  apps/agent/src/pages/couriers/register/[...step].tsx
  apps/agent/src/pages/suppliers/register/[[...step]].tsx
  packages/lib/formStore.ts
  packages/lib/index.ts
  packages/ui/Input.tsx
  packages/ui/Select.tsx
Labels: enhancement 🌻, work_in_progress 🐣, front-end 🦋, backend 🐝

#71 [SAH-35]: Improve Businesses List and Businesses Details Page
  apps/agent/src/Businesses/BusinessOrderHistory.tsx
  apps/agent/src/Businesses/BusinessOverviewCard.tsx
  apps/agent/src/Businesses/BusinessProfileOverview.tsx
  apps/agent/src/Businesses/ListBusinesses.tsx
  apps/agent/src/hooks/businesses.ts
  apps/agent/src/lib/graphql/queries/businesses.ts
  apps/agent/src/pages/businesses/[businessId].tsx
  apps/agent/src/pages/businesses/index.tsx
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#92 [SAH-46]: Order progress tracking
  apps/admin/src/Agents/AgentOverviewCard.tsx
  apps/admin/src/Agents/AgentRegistrationForm/index.tsx
  apps/admin/src/Agents/ListAgents.tsx
  apps/agent/package.json
  apps/agent/src/Businesses/BusinessOrderHistory.tsx
  apps/agent/src/Businesses/BusinessOverviewCard.tsx
  apps/agent/src/Couriers/CourierOverviewCard.tsx
  apps/agent/src/Couriers/CourierStats.tsx
  apps/agent/src/Orders/CourierOverview.tsx
  apps/agent/src/Orders/OrderClient.tsx
  apps/agent/src/Orders/OrderDetails.tsx
  apps/agent/src/Orders/OrderItems.tsx
  apps/agent/src/Orders/OrderOverview.tsx
  apps/agent/src/Orders/OrderOverviewCard.tsx
  apps/agent/src/Orders/OrderPreferences.tsx
  apps/agent/src/Orders/OrderProgress.tsx
  apps/agent/src/Orders/OrderStatusSteps.tsx
  apps/agent/src/Orders/index.ts
  apps/agent/src/Suppliers/SupplierOrderHistory.tsx
  apps/agent/src/Suppliers/SupplierOverviewCard.tsx
  apps/agent/src/Suppliers/SupplierProductList.tsx
  apps/agent/src/hooks/businesses.ts
  apps/agent/src/hooks/orders.ts
  apps/agent/src/hooks/suppliers.ts
  apps/agent/src/lib/graphql/queries/businesses.ts
  apps/agent/src/lib/graphql/queries/orders.ts
  apps/agent/src/lib/graphql/queries/suppliers.ts
  apps/agent/src/pages/orders/[orderId].tsx
  apps/agent/src/pages/orders/track.tsx
  apps/agent/src/pages/suppliers/[supplierId].tsx
  apps/agent/tailwind.config.ts
  packages/ui/components/Avatar.tsx
  packages/ui/components/Card/Card.tsx
  packages/ui/components/IconButton.tsx
  packages/ui/components/ProfileOverviewCard.tsx
  packages/ui/components/Tabs.tsx
  packages/ui/index.tsx
  packages/ui/package.json
  yarn.lock
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#98 [SAH-47]: Add font and cleanup Client
  apps/client/src/pages/_document.tsx
  apps/client/src/pages/index.tsx
  apps/client/src/pages/orders/index.tsx
  apps/client/src/pages/payments/index.tsx
  apps/client/src/pages/products/index.tsx
  apps/client/src/pages/support/index.tsx
  apps/client/src/styles/globals.css
  packages/ui/components/SidebarWrapper.tsx
  packages/ui/components/Wrapper.tsx
  packages/ui/index.tsx
Labels: enhancement 🌻, good first issue 🌈, front-end 🦋
