Repository Sahil-Connect/sahil, pull requests merged in 2024-01, with the labels that each got.

#105 Init Express API
  apps/api/package.json
  apps/api/src/app.ts
  apps/api/src/config.ts
  apps/api/src/db.ts
  apps/api/src/enqueue.ts
  apps/api/src/init.ts
  apps/api/src/queue.ts
  apps/api/src/routers/api.ts
  apps/api/src/routers/index.ts
  apps/api/src/server.ts
  apps/api/src/users/router.ts
  apps/api/tsconfig.json
  yarn.lock
Labels: enhancement 🌻, work_in_progress 🐣, backend 🐝, infra 🏭

#114 [SAH-48]: Dockerize Sahil
  .dockerignore
  README.md
  apps/agent/src/Businesses/ListBusinesses.tsx
  apps/agent/src/Layout/layout.tsx
  apps/agent/src/Suppliers/SupplierRegistrationForm/SupplierBasicInfoForm.tsx
  apps/client/src/Businesses/ListBusinesses.tsx
  apps/website/next.config.js
  apps/website/package.json
  apps/website/src/components/Sections/Faqs.tsx
  docker-compose.yml
  infra/docker/Dockerfile.website
Labels: work_in_progress 🐣, infra 🏭

#115 Orders API
  .gitignore
  apps/api/package.json
  apps/api/src/enqueue.ts
  apps/api/src/init.ts
  apps/api/src/lib/ioredis.ts
  apps/api/src/lib/winston.ts
  apps/api/src/middleware/errors.ts
  apps/api/src/middleware/requestLogger.ts
  apps/api/src/middleware/zodValidate.ts
  apps/api/src/orders/operations/initOrder.ts
  apps/api/src/orders/operations/processOrder.ts
  apps/api/src/orders/router.ts
  apps/api/src/orders/worker.ts
  apps/api/src/queue.ts
  apps/api/src/routers/api.ts
  apps/api/src/server.ts
  apps/api/src/workers.ts
  yarn.lock
Labels: enhancement 🌻, ready_for_review 🍀, backend 🐝, infra 🏭

#102 Refactor GQL
  .vscode/settings.json
  apps/agent/src/hooks/businesses.ts
  apps/agent/src/hooks/couriers.ts
  apps/agent/src/hooks/orders.ts
  apps/agent/src/hooks/products.ts
  apps/agent/src/hooks/suppliers.ts
  apps/agent/src/hooks/users.ts
  apps/agent/src/lib/graphql/apolloClient.ts
  apps/agent/src/lib/graphql/mutations/locations.ts
  apps/agent/src/lib/graphql/mutations/payments.ts
  apps/agent/src/lib/graphql/queries/products.ts
  apps/agent/src/pages/_app.tsx
  apps/agent/src/pages/businesses/[businessId].tsx
  apps/client/src/hooks/accounts.ts
  apps/client/src/hooks/businesses.ts
  apps/client/src/hooks/orders.ts
  apps/client/src/hooks/payments.ts
  apps/client/src/hooks/products.ts
  apps/client/src/hooks/useOrderItemsStore.ts
  apps/client/src/hooks/users.ts
  apps/client/src/lib/graphql/apolloClient.ts
  apps/client/src/lib/graphql/mutations/businesses.ts
  apps/client/src/lib/graphql/mutations/orders.ts
  apps/client/src/lib/graphql/mutations/payments.ts
  apps/client/src/lib/graphql/queries/accounts.ts
  apps/client/src/lib/graphql/queries/businesses.ts
  apps/client/src/lib/graphql/queries/orders.ts
  apps/client/src/lib/graphql/queries/payments.ts
  apps/client/src/lib/graphql/queries/users.ts
  apps/client/src/pages/_app.tsx
  packages/lib/graphql/createApolloClient.ts
  packages/lib/graphql/index.ts
  packages/lib/graphql/mutations/businesses.ts
  packages/lib/graphql/mutations/couriers.ts
  packages/lib/graphql/mutations/locations.ts
  packages/lib/graphql/mutations/orders.ts
  packages/lib/graphql/mutations/suppliers.ts
  packages/lib/graphql/mutations/users.ts
  packages/lib/graphql/queries/businesses.ts
  packages/lib/graphql/queries/couriers.ts
  packages/lib/graphql/queries/locations.ts
  packages/lib/graphql/queries/momo.ts
  packages/lib/graphql/queries/orders.ts
  packages/lib/graphql/queries/products.ts
  packages/lib/graphql/queries/suppliers.ts
  packages/lib/graphql/queries/users.ts
Labels: enhancement 🌻, ready_for_review 🍀

#125 [SAH-50]: Push Notifications
  apps/agent/package.json
  apps/agent/public/worker.js
  apps/agent/tsconfig.json
  apps/api/src/config.ts
  apps/api/src/lib/webPush.ts
  apps/api/src/notifications/router.ts
  apps/api/src/routers/api.ts
  packages/lib/web-push/index.ts
  yarn.lock
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#132 [SAH-64]: Setup a Custom Remote Cache Server
  .env.example
  apps/api/src/routers/home.ts
  apps/api/src/routers/index.ts
  docker-compose.yml
  infra/docker/Dockerfile.website
  infra/terraform/remote-cache-server/.gitignore
  infra/terraform/remote-cache-server/README.md
  infra/terraform/remote-cache-server/functions/index.js
  infra/terraform/remote-cache-server/functions/package.json
  infra/terraform/remote-cache-server/terraform/.terraform.lock.hcl
  infra/terraform/remote-cache-server/terraform/artifact_registry.tf
  infra/terraform/remote-cache-server/terraform/cloud_functions.tf
  infra/terraform/remote-cache-server/terraform/cloud_run.tf
  infra/terraform/remote-cache-server/terraform/cloud_storage.tf
  infra/terraform/remote-cache-server/terraform/locals.tf
  infra/terraform/remote-cache-server/terraform/provider.tf
  infra/terraform/remote-cache-server/terraform/pubsub.tf
  infra/terraform/remote-cache-server/terraform/secret_manager.tf
  infra/terraform/remote-cache-server/terraform/service_account.tf
  infra/terraform/remote-cache-server/terraform/variables.tf
  infra/terraform/remote-cache-server/terraform/version.tf
  package.json
  turbo.json
Labels: ready_for_review 🍀, backend 🐝, infra 🏭

#134 [SAH-39]: Sort Products in Supplier Page
  .github/workflows/website-staging.yml
  apps/agent/src/Businesses/BusinessOrderHistory.tsx
  apps/agent/src/Businesses/ListBusinesses.tsx
  apps/agent/src/Couriers/ListCouriers.tsx
  apps/agent/src/Orders/ListOrders.tsx
  apps/agent/src/Suppliers/ListSuppliers.tsx
  apps/agent/src/Suppliers/SupplierOrderHistory.tsx
  apps/agent/src/Suppliers/SupplierProductList.tsx
  apps/agent/src/Suppliers/SupplierProducts.tsx
  apps/agent/src/hooks/suppliers.ts
  apps/client/src/Businesses/BusinessOrderHistory.tsx
  apps/client/src/Businesses/ListBusinesses.tsx
  apps/client/src/Orders/OrderHistory.tsx
  apps/client/src/Products/ProductsCatalogue.tsx
  apps/client/src/pages/checkout/index.tsx
  packages/lib/graphql/queries/suppliers.ts
  packages/ui/components/List/ListHeader.tsx
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋

#131 [SAH-60]: Implement Order Processing Validation
  apps/agent/src/pages/_app.tsx
  apps/api/src/middleware/zodValidate.ts
  apps/api/src/orders/router.ts
  apps/client/src/Products/ProductsCatalogue.tsx
  apps/client/src/hooks/orders.ts
  apps/client/src/hooks/products.ts
  apps/client/src/hooks/useOrderItemsStore.ts
  apps/client/src/pages/_app.tsx
  apps/client/src/pages/checkout/index.tsx
  packages/lib/graphql/__generated__/gql.ts
  packages/lib/graphql/__generated__/graphql.ts
  packages/lib/graphql/createApolloClient.ts
  packages/lib/graphql/index.ts
  packages/lib/graphql/mutations/orders.ts
  packages/lib/graphql/subscriptions/orders.ts
  packages/lib/hooks/payments.ts
Labels: enhancement 🌻, ready_for_review 🍀, front-end 🦋, backend 🐝

#137 Update README.md
  README.md
Labels: documentation 🦉, enhancement 🌻, work_in_progress 🐣
